In [1]:
import duckdb
import pandas as pd

In [2]:
sql_query = '''
show tables
'''


with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2             gold_ticket_metrics
3           gold_vehicles_metrics
4          parking_violation_2023
5         parking_violation_codes
6  silver_parking_violation_codes
7       silver_parking_violations
8        silver_violation_tickets
9       silver_violation_vehicles

In [5]:
select_query = ''' 
  select * from "nyc_parking_violations"."main_dbt_test__audit"."unique_bronze_parking_violations_violation_code"
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(select_query).df())

    unique_field  n_records
0              0         14
1              4          5
2              5       3477
3              6         34
4              7       4055
..           ...        ...
66            89          9
67            91          2
68            95          4
69            98        298
70            99         26

[71 rows x 2 columns]

In [4]:
sql_query_import1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT * 
FROM read_csv_auto(
  'data/dof_parking_violation_codes.csv',
  normalize_names=True
)
'''
sql_query_import2 = '''
CREATE OR REPLACE TABLE parking_violation_2023 AS
SELECT * 
FROM read_csv_auto(
  'data/parking_violations_issued_fiscal_year_2023_sample.csv',
  normalize_names=True
)
'''
with duckdb.connect('data/nyc_parking_violations.db') as con:
  con.sql(sql_query_import1)
  con.sql(sql_query_import2)

# Create production database

In [6]:
sql_query_import1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT * 
FROM read_csv_auto(
  'data/dof_parking_violation_codes.csv',
  normalize_names=True
)
'''
sql_query_import2 = '''
CREATE OR REPLACE TABLE parking_violation_2023 AS
SELECT * 
FROM read_csv_auto(
  'data/parking_violations_issued_fiscal_year_2023_sample.csv',
  normalize_names=True
)
'''
with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
  con.sql(sql_query_import1)
  con.sql(sql_query_import2)

In [7]:
sql_query = '''
show tables
'''


with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2             gold_ticket_metrics
3           gold_vehicles_metrics
4          parking_violation_2023
5         parking_violation_codes
6         parking_violations_2023
7        silver_violation_tickets
8       silver_violation_vehicles